import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {

  createDb() {
    let heroes = [  
      {id: 1, name: 'Aatrox', img: 'Aatrox.png'},
      {id: 2, name: 'Ahri', img: 'Ahri.png'},
      {id: 3, name: 'Akali', img: 'Akali.png'},
      {id: 4, name: 'Alistar', img: 'Alistar.png'},
      {id: 5, name: 'Amumu', img: 'Amumu.png'},
      {id: 6, name: 'Anivia', img: 'Anivia.png'},
      {id: 7, name: 'Annie', img: 'Annie.png'},
      {id: 8, name: 'Ashe', img: 'Ashe.png'},
      {id: 9, name: 'Aurelion Sol', img: 'AurelionSol.png'},
      {id: 10, name: 'Azir', img: 'Azir.png'},
      {id: 11, name: 'Bard', img: 'Bard.png'},
      {id: 12, name: 'Blitzcrank', img: 'Blitzcrank.png'},
      {id: 13, name: 'Brand', img: 'Brand.png'},
      {id: 14, name: 'Braum', img: 'Braum.png'},
      {id: 15, name: 'Caitlyn', img: 'Caitlyn.png'},
      {id: 16, name: 'Camille', img: 'Camille.png'},
      {id: 17, name: 'Cassiopeia', img: 'Cassiopeia.png'},
      {id: 18, name: 'Cho\'gath', img: 'Chogath.png'},
      {id: 19, name: 'Corki', img: 'Corki.png'},
      {id: 20, name: 'Darius', img: 'Darius.png'},
      {id: 21, name: 'Diana', img: 'Diana.png'},
      {id: 22, name: 'Draven', img: 'Draven.png'},
      {id: 23, name: 'Dr. Mundo', img: 'DrMundo.png'},
      {id: 24, name: 'Ekko', img: 'Ekko.png'},
      {id: 25, name: 'Elise', img: 'Elise.png'},
      {id: 26, name: 'Evelynn', img: 'Evelynn.png'},
      {id: 27, name: 'Ezreal', img: 'Ezreal.png'},
      {id: 28, name: 'FiddleSticks', img: 'FiddleSticks.png'},
      {id: 29, name: 'Fiora', img: 'Fiora.png'},
      {id: 30, name: 'Fizz', img: 'Fizz.png'},
      {id: 31, name: 'Galio', img: 'Galio.png'},
      {id: 32, name: 'Gangplank', img: 'Gangplank.png'},
      {id: 33, name: 'Garen', img: 'Garen.png'},
      {id: 34, name: 'Gnar', img: 'Gnar.png'},
      {id: 35, name: 'Gragas', img: 'Gragas.png'},
      {id: 36, name: 'Graves', img: 'Graves.png'},
      {id: 37, name: 'Hecarim', img: 'Hecarim.png'},
      {id: 38, name: 'Heimerdinger', img: 'Heimerdinger.png'},
      {id: 39, name: 'Illaoi', img: 'Illaoi.png'},
      {id: 40, name: 'Irelia', img: 'Irelia.png'},
      {id: 41, name: 'Ivern', img: 'Ivern.png'},
      {id: 42, name: 'Janna', img: 'Janna.png'},
      {id: 43, name: 'Jarvan IV', img: 'JarvanIV.png'},
      {id: 44, name: 'Jax', img: 'Jax.png'},
      {id: 45, name: 'Jayce', img: 'Jayce.png'},
      {id: 46, name: 'Jhin', img: 'Jhin.png'},
      {id: 47, name: 'Jinx', img: 'Jinx.png'},
      {id: 48, name: 'Kalista', img: 'Kalista.png'},
      {id: 49, name: 'Karma', img: 'Karma.png'},
      {id: 50, name: 'Karthus', img: 'Karthus.png'},
      {id: 51, name: 'Kassadin', img: 'Kassadin.png'},
      {id: 52, name: 'Katarina', img: 'Katarina.png'},
      {id: 53, name: 'Kayle', img: 'Kayle.png'},
      {id: 54, name: 'Kennen', img: 'Kennen.png'},
      {id: 55, name: 'Kha\'zix', img: 'Khazix.png'},
      {id: 56, name: 'Kindred', img: 'Kindred.png'},
      {id: 57, name: 'Kled', img: 'Kled.png'},
      {id: 58, name: 'Kog\'Maw', img: 'KogMaw.png'},
      {id: 59, name: 'Leblanc', img: 'Leblanc.png'},
      {id: 60, name: 'LeeSin', img: 'LeeSin.png'},
      {id: 61, name: 'Leona', img: 'Leona.png'},
      {id: 62, name: 'Lissandra', img: 'Lissandra.png'},
      {id: 63, name: 'Lucian', img: 'Lucian.png'},
      {id: 64, name: 'Lulu', img: 'Lulu.png'},
      {id: 65, name: 'Lux', img: 'Lux.png'},
      {id: 66, name: 'Malphite', img: 'Malphite.png'},
      {id: 67, name: 'Malzahar', img: 'Malzahar.png'},
      {id: 68, name: 'Maokai', img: 'Maokai.png'},
      {id: 69, name: 'Master Yi', img: 'MasterYi.png'},
      {id: 70, name: 'Miss Fortune', img: 'MissFortune.png'},
      {id: 71, name: 'Monkey King', img: 'MonkeyKing.png'},
      {id: 72, name: 'Mordekaiser', img: 'Mordekaiser.png'},
      {id: 73, name: 'Morgana', img: 'Morgana.png'},
      {id: 74, name: 'Nami', img: 'Nami.png'},
      {id: 75, name: 'Nasus', img: 'Nasus.png'},
      {id: 76, name: 'Nautilus', img: 'Nautilus.png'},
      {id: 77, name: 'Nidalee', img: 'Nidalee.png'},
      {id: 78, name: 'Nocturne', img: 'Nocturne.png'},
      {id: 79, name: 'Nunu', img: 'Nunu.png'},
      {id: 80, name: 'Olaf', img: 'Olaf.png'},
      {id: 81, name: 'Orianna', img: 'Orianna.png'},
      {id: 82, name: 'Pantheon', img: 'Pantheon.png'},
      {id: 83, name: 'Poppy', img: 'Poppy.png'},
      {id: 84, name: 'Quinn', img: 'Quinn.png'},
      {id: 85, name: 'Rammus', img: 'Rammus.png'},
      {id: 86, name: 'Rek\'Sai', img: 'RekSai.png'},
      {id: 87, name: 'Renekton', img: 'Renekton.png'},
      {id: 88, name: 'Rengar', img: 'Rengar.png'},
      {id: 89, name: 'Riven', img: 'Riven.png'},
      {id: 90, name: 'Rumble', img: 'Rumble.png'},
      {id: 91, name: 'Ryze', img: 'Ryze.png'},
      {id: 92, name: 'Sejuani', img: 'Sejuani.png'},
      {id: 93, name: 'Shaco', img: 'Shaco.png'},
      {id: 94, name: 'Shen', img: 'Shen.png'},
      {id: 95, name: 'Shyvana', img: 'Shyvana.png'},
      {id: 96, name: 'Singed', img: 'Singed.png'},
      {id: 97, name: 'Sion', img: 'Sion.png'},
      {id: 98, name: 'Sivir', img: 'Sivir.png'},
      {id: 99, name: 'Skarner', img: 'Skarner.png'},
      {id: 100, name: 'Sona', img: 'Sona.png'},
      {id: 101, name: 'Soraka', img: 'Soraka.png'},
      {id: 102, name: 'Swain', img: 'Swain.png'},
      {id: 103, name: 'Syndra', img: 'Syndra.png'},
      {id: 104, name: 'Tahm Kench', img: 'TahmKench.png'},
      {id: 105, name: 'Taliyah', img: 'Taliyah.png'},
      {id: 106, name: 'Talon', img: 'Talon.png'},
      {id: 107, name: 'Taric', img: 'Taric.png'},
      {id: 108, name: 'Teemo', img: 'Teemo.png'},
      {id: 109, name: 'Thresh', img: 'Thresh.png'},
      {id: 110, name: 'Tristana', img: 'Tristana.png'},
      {id: 111, name: 'Trundle', img: 'Trundle.png'},
      {id: 112, name: 'Tryndamere', img: 'Tryndamere.png'},
      {id: 113, name: 'Twisted Fate', img: 'TwistedFate.png'},
      {id: 114, name: 'Twitch', img: 'Twitch.png'},
      {id: 115, name: 'Udyr', img: 'Udyr.png'},
      {id: 116, name: 'Urgot', img: 'Urgot.png'},
      {id: 117, name: 'Varus', img: 'Varus.png'},
      {id: 118, name: 'Vayne', img: 'Vayne.png'},
      {id: 119, name: 'Veigar', img: 'Veigar.png'},
      {id: 120, name: 'Vel\'koz', img: 'Velkoz.png'},
      {id: 121, name: 'Viktor', img: 'Viktor.png'},
      {id: 122, name: 'Vi', img: 'Vi.png'},
      {id: 123, name: 'Vladimir', img: 'Vladimir.png'},
      {id: 124, name: 'Volibear', img: 'Volibear.png'},
      {id: 125, name: 'Warwick', img: 'Warwick.png'},
      {id: 126, name: 'Xerath', img: 'Xerath.png'},
      {id: 127, name: 'Xin Zhao', img: 'XinZhao.png'},
      {id: 128, name: 'Yasuo', img: 'Yasuo.png'},
      {id: 129, name: 'Yorick', img: 'Yorick.png'},
      {id: 130, name: 'Zac', img: 'Zac.png'},
      {id: 131, name: 'Zed', img: 'Zed.png'},
      {id: 132, name: 'Ziggs', img: 'Ziggs.png'},
      {id: 133, name: 'Zilean', img: 'Zilean.png'},
      {id: 134, name: 'Zyra', img: 'Zyra.png'},
    ];
    
    return {heroes};
  }
}